services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./monitoring/predictions_log.jsonl:/app/monitoring/predictions_log.jsonl

  dashboard:
    build: .
    ports:
      - "8501:8501"
    command: uv run streamlit run monitoring/dashboard.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./monitoring/predictions_log.jsonl:/app/monitoring/predictions_log.jsonl
      - ./data/test_preprocessed.csv:/app/data/test_preprocessed.csv
    depends_on:
      - api
